### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by santux-** [jeffbonhag/db2-docker#9]
Hi Jeff,
             I keep getting this error during the build:
[..]
Task #38 start
Description: Updating global profile registry
Estimated time 3 second(s)
Task #38 end

A minor error occurred while installing "DB2 Express-C " on this computer.
Some features may not function correctly.

For more information see the DB2 installation log at
"/tmp/db2_install.log.7".
2015/01/28 18:18:11 The command [/bin/sh -c /cache/expc/db2_install -b /opt/ibm/db2/V10.5] returned a non-zero code: 1

Any clue of what could I've been doing wrong/missing or how can I get more details about this error?

Docker version 1.1.2, build d84a070/1.1.2 

Thanks!

**Comment by jeffbonhag** [comment]
Hi @santux- 

I just ran through an install, here's the relevant part of the log:

```
ERROR: The installation of the license file 
"/tmp/db2.tmp.7/db2/linuxamd64/install/../../license/db2expc_uw.lic" using the 
command "/opt/ibm/db2/V10.5/adm/db2licm -a 
"/tmp/db2.tmp.7/db2/linuxamd64/install/../../license/db2expc_uw.lic" -install" 
did not complete successfully. The error data is "". The Return value was 
"127".

Registering DB2 licenses :.......Failure 
ERROR: The value "DB2SYSTEM=f4f502dce15c" could not be added to the Global 
Profile Registry. Return value is "127".

ERROR: The value "DB2_COMPATIBILITY_VECTOR=MYS" could not be added to the 
Global Profile Registry. Return value is "127".

Setting default global profile registry variables :.......Failure 
Initializing instance list :.......Success 
Registering DB2 Update Service :.......Success 
Updating global profile registry :.......Success 
WARNING: A minor error occurred while installing "DB2 Express-C " on this 
computer. Some features may not function correctly.
```

I'm not sure what's causing that.  My only trick so far has been to switch to the devicemapper backend (I hear btrfs works reliably, too).

I suggest giving @angoca 's DB2 container a try at https://github.com/angoca/db2-docker.

**Comment by santux-** [comment]
Thanks for your reply! I've been working on it and I have my own Dockerfile working! :)

**Comment by angoca** [comment]
Hi @santux- I created a set of DB2 containers for different puposes. Also, there is a a community dedicated for DB2 projects. I would like to know if you are creating something specific for you or general purpose. I ask you that, because we are trying to work together in a set of container for DB2.
Take a look at my containers: https://hub.docker.com/u/angoca/
They download db2, install it, create instance and create database sample.
If you want to work with us or provide more option, please join the db2-coders community.

**Comment by jeffbonhag** [comment]
@santux- Nice, congratulations!  Mind if I close the issue?

**Comment by jeffbonhag** [comment]
:+1:
